### ISSUE TITLE
Querying animals by organization_id does not work

### ISSUE THREAD

**Issue by edmcman** [aschleg/petpy#14]
Very similar problem as in PetfindeR which I fixed here:

https://github.com/aschleg/PetfindeR/pull/3

**Comment by aschleg** [comment]
Thanks again for finding that issue and submitting a pull request! Confirming the pull request has been merged with the main branch and will get an update to CRAN as soon as I can.

**Comment by micahwierenga** [comment]
Has this issue been resolved? Trying to query `pf.animals(animal_type='dog', organization_id='CO385')` and it returns seemingly random organizations.

**Comment by edmcman** [comment]
I'm looking back, and I don't think I ever made a PR for this project (but did for PetfindeR).  Maybe @aschleg thought this was a bug in PetfindeR and was closed by merging that PR?

**Comment by micahwierenga** [comment]
Interesting! I was wondering if it was resolved. We've followed the docs (https://petpy.readthedocs.io/en/latest/api.html), but that `organization_id` seems to be ignored when querying `Petfinder.animals`. Thanks for the quick response!!

**Comment by aschleg** [comment]
Hi Hi Everyone,

Apologies for the delay in my reply! I just released a new version of petpy, 2.1.3, that should resolve the issue of the `animals()` method not recognizing if one or more organization IDs were passed as well. Thank you so much for letting me know there was an issue with the method and please let me know if you have any questions!

Aaron
