### ISSUE TITLE
animal_type parameter does not work

### ISSUE THREAD

**Issue by ma7555** [aschleg/petpy#16]
Hello,
specifing animal_type in the animals call does not work and the returned df contains all animals

```pf.animals(results_per_page=50, pages=1, return_df=True, animal_type='cat')```

![image](https://user-images.githubusercontent.com/7144929/69269472-c0e0fb00-0bd9-11ea-9355-94a7dbdd5309.png)

**Comment by ma7555** [comment]
I have identified the problem and will create a PR soon, it is not a problem in your code though but rather on their side

**Comment by aschleg** [comment]
Hello! 

Thank you so much for investigating the issue and submitting a pull request! As I mentioned on the pull request, I went ahead and merged it and will release a new version of `petpy` on PyPI shortly. Thanks again for your help!
