### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by zhangluustb** [aschleg/petpy#21]
AT line pf = petpy.Petfinder(key,secret)
--> 107         return r.json()['access_token']
    108 
    109     def animal_types(self, types=None):

KeyError: 'access_token'

**Comment by aschleg** [comment]
Hello!

I looked into this and I wasn't able to replicate. Did you make sure to get an API and secret key from Petfinder.com by creating an account at https://www.petfinder.com/developers/? You need to pass in these keys when initializing the `Petfinder` class. Please let me know if this helps.

That said, I realize there could probably be some better error messages to help users debug any issues, so thank you for bringing that to my attention!

**Comment by zhangluustb** [comment]
It works finally, I guess it might be something writing wrong by my own, or the Internet's problem. Thanks for your help^-^
