### ISSUE TITLE
Should pandas be added to install_requires?

### ISSUE THREAD

**Issue by crew102** [aschleg/petpy#8]
Given that you have:

https://github.com/aschleg/petpy/blob/fd2f63290d6e77ececc2a330d9a6d1d431084337/petpy/api.py#L4-L5

Should you not include pandas in `install_requires`? Users will get an import error re: no installation of pandas found if they don't install pandas manually after installing petpy.

**Comment by aschleg** [comment]
Hello!

Thanks a lot for pointing that out! You're totally right, I did originally have pandas as an installation requirement but I removed it in a later version as I wanted to keep the dependencies minimal. Completely did not realize it was still in the imports section, duh! I am preparing a small update release that includes pandas >= 0.22.0 as an installation requirement and will have that out likely by tomorrow morning.

Thanks again for your help!

**Comment by aschleg** [comment]
Version 1.8.2 has been released on PyPI and the latest commit 71ece83 returns `pandas` as an installation requirement.
